/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author athar
 */
public class UpdatePersonJPanel extends javax.swing.JPanel {
    PersonDirectory personDirectory;
    Person person;
    JPanel WorkArea;
    private Address homeaddress;
    private Address workaddress;
    private JTable tblViewPerson;
    private ViewPersonJPanel viewPanel;

    /**
     * Creates new form UpdatePersonJPanel
     */
    public UpdatePersonJPanel(ViewPersonJPanel viewPanel,JPanel WorkArea, PersonDirectory personDirectory, Person person, Address homeaddress, Address workaddress,JTable tblViewPerson) {
        initComponents();
        this.personDirectory=personDirectory;
        this.viewPanel = viewPanel;
        this.person=person;
        this.WorkArea=WorkArea;
        this.workaddress= new Address();
        this.homeaddress= new Address();
        this.tblViewPerson = tblViewPerson;
        //to populate the JPanel with the Person data
        populateFields();
        setFieldsReadOnly();
        System.out.println("txtFirstName editable: " + txtFirstName.isEditable());
    }
    private void setFieldsReadOnly() {
        // Make each text field read-only
        txtFirstName.setEditable(false);
        txtLastName.setEditable(false);
        txtAge.setEditable(false);
        txtSocialNumber.setEditable(false);
        txtStreetName.setEditable(false);
        txtUnitNumber.setEditable(false);
        txtCity.setEditable(false);
        txtState.setEditable(false);
        txtZip.setEditable(false);
        txtPhoneNumber.setEditable(false);
        txtWorkStreetName.setEditable(false);
        txtWorkCity.setEditable(false);
        txtWorkState.setEditable(false);
        txtWorkZip.setEditable(false);
        txtWorkPhoneNumber.setEditable(false);
        Color grayForeground = new Color(150, 150, 150);
        
        
        txtFirstName.setBackground(grayForeground);
        txtLastName.setBackground(grayForeground);
        txtAge.setBackground(grayForeground);
        txtSocialNumber.setBackground(grayForeground);
        txtStreetName.setBackground(grayForeground);
        txtUnitNumber.setBackground(grayForeground);
        txtCity.setBackground(grayForeground);
        txtState.setBackground(grayForeground);
        txtZip.setBackground(grayForeground);
        txtPhoneNumber.setBackground(grayForeground);
        txtWorkStreetName.setBackground(grayForeground);
        txtWorkUnitNumber.setBackground(grayForeground);
        txtWorkCity.setBackground(grayForeground);
        txtWorkState.setBackground(grayForeground);
        txtWorkZip.setBackground(grayForeground);
        txtWorkPhoneNumber.setBackground(grayForeground);
    }
    private void populateFields(){
        txtFirstName.setText(person.getFirstname());
        txtLastName.setText(person.getLastname());
        txtAge.setText(Integer.toString(person.getAge()));
        txtSocialNumber.setText(person.getSocialNumber());
        txtStreetName.setText(person.getHomeAddress().getStreetAddress());
        txtUnitNumber.setText(Integer.toString(person.getHomeAddress().getUnitName()));
        txtCity.setText(person.getHomeAddress().getCity());
        txtState.setText(person.getHomeAddress().getState());
        txtZip.setText(Integer.toString(person.getHomeAddress().getZipCode()));
        txtPhoneNumber.setText(person.getHomeAddress().getPhoneNumber());
        
        
        txtWorkStreetName.setText(person.getWorkAddress().getStreetAddress());
        txtWorkUnitNumber.setText(Integer.toString(person.getWorkAddress().getUnitName()));
        txtWorkCity.setText(person.getWorkAddress().getCity());
        txtWorkState.setText(person.getWorkAddress().getState());
        txtWorkZip.setText(Integer.toString(person.getWorkAddress().getZipCode()));
        txtWorkPhoneNumber.setText(person.getWorkAddress().getPhoneNumber());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtState = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblWorkUnitNumber = new javax.swing.JLabel();
        txtWorkUnitNumber = new javax.swing.JTextField();
        lblWorkCity = new javax.swing.JLabel();
        txtWorkCity = new javax.swing.JTextField();
        lblWorkState = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtSocialNumber = new javax.swing.JTextField();
        lblHomeTitle = new javax.swing.JLabel();
        lblStreetName = new javax.swing.JLabel();
        txtStreetName = new javax.swing.JTextField();
        lblUnitNumber = new javax.swing.JLabel();
        txtUnitNumber = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtWorkState = new javax.swing.JTextField();
        lblMainTitle = new javax.swing.JLabel();
        lblWorkPhoneNumber = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtWorkZip = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblWorkZip = new javax.swing.JLabel();
        lblSocialNumber = new javax.swing.JLabel();
        txtWorkPhoneNumber = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblWorkTitle = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblWorkStreetName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtWorkStreetName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));

        lblPhoneNumber.setText("Phone Number");

        lblZip.setText("Zip");

        lblWorkUnitNumber.setText("Unit Number");

        lblWorkCity.setText("City");

        lblWorkState.setText("State");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtSocialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocialNumberActionPerformed(evt);
            }
        });

        lblHomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHomeTitle.setText("Home Address");

        lblStreetName.setText("Street Address");

        lblUnitNumber.setText("Unit Number");

        lblCity.setText("City");

        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblMainTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMainTitle.setText("Update Person");

        lblWorkPhoneNumber.setText("Phone Number");

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblWorkZip.setText("Zip");

        lblSocialNumber.setText("Social Security Number");

        lblAge.setText("Age");

        lblWorkTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWorkTitle.setText("Work Address");

        lblWorkStreetName.setText("Street Address");

        lblState.setText("State");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSocialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblWorkZip, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtWorkZip, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(txtWorkCity)
                                                            .addComponent(txtWorkStreetName)
                                                            .addComponent(lblWorkStreetName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(lblWorkTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lblWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(40, 40, 40)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtWorkPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtWorkState, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtWorkUnitNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblWorkState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblWorkPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblWorkUnitNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(29, 29, 29))))))
                            .addComponent(txtSocialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtZip, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtStreetName)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblStreetName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHomeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblZip, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(140, 140, 140)
                        .addComponent(btnUpdate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtState, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(149, 149, 149))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnitNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(178, 178, 178)))
                        .addGap(333, 333, 333))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(lblFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialNumber)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSocialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblHomeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreetName)
                            .addComponent(lblUnitNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(lblState))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNumber)
                            .addComponent(lblZip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblWorkTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWorkStreetName)
                            .addComponent(lblWorkUnitNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWorkStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWorkUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWorkCity)
                            .addComponent(lblWorkState))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWorkPhoneNumber)
                            .addComponent(lblWorkZip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWorkZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWorkPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //Change the background and editible to true
        setFieldsEditable();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSocialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocialNumberActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Person person = new Person();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        int age = Integer.parseInt(txtAge.getText()); // Convert age to int
        String socialNumber = txtSocialNumber.getText();
        String streetAddress = txtStreetName.getText();
        Integer unitNumber = Integer.valueOf(txtUnitNumber.getText());
        String city = txtCity.getText();
        String state = txtState.getText();
        Integer zipCode = Integer.valueOf(txtZip.getText());
        String phoneNumber = txtPhoneNumber.getText();
        String workstreetAddress = txtWorkStreetName.getText();
        Integer workunitNumber = Integer.valueOf(txtWorkUnitNumber.getText());
        String workcity = txtWorkCity.getText();
        String workstate = txtWorkState.getText();
        Integer workzipCode = Integer.valueOf(txtWorkZip.getText());
        String workphoneNumber = txtWorkPhoneNumber.getText();
        
        person.setFirstname(firstName);
        person.setLastname(lastName);
        person.setAge(age);
        person.setSocialNumber(socialNumber);
        person.getHomeAddress().setStreetAddress(streetAddress);
        person.getHomeAddress().setZipCode(zipCode);
        person.getHomeAddress().setCity(city);
        person.getHomeAddress().setState(state);
        person.getHomeAddress().setUnitName(unitNumber);
        person.getHomeAddress().setPhoneNumber(phoneNumber);
        person.getWorkAddress().setStreetAddress(workstreetAddress);
        person.getWorkAddress().setZipCode(workzipCode);
        person.getWorkAddress().setCity(workcity);
        person.getWorkAddress().setState(workstate);
        person.getWorkAddress().setUnitName(workunitNumber);
        person.getWorkAddress().setPhoneNumber(workphoneNumber); 
        
        boolean success = personDirectory.updatePerson(person);
        if (success) {
        // Show success message
        JOptionPane.showMessageDialog(this, "Person updated successfully!");
        setFieldsReadOnly();
        System.out.println(zipCode);
        
        populateTable();//this is unable to refresh here
    } else {
        JOptionPane.showMessageDialog(this, "Error updating person. Person not found.");
      }
      
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        WorkArea.remove(this);
        CardLayout layout=(CardLayout)WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeTitle;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSocialNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JLabel lblWorkCity;
    private javax.swing.JLabel lblWorkPhoneNumber;
    private javax.swing.JLabel lblWorkState;
    private javax.swing.JLabel lblWorkStreetName;
    private javax.swing.JLabel lblWorkTitle;
    private javax.swing.JLabel lblWorkUnitNumber;
    private javax.swing.JLabel lblWorkZip;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSocialNumber;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetName;
    private javax.swing.JTextField txtUnitNumber;
    private javax.swing.JTextField txtWorkCity;
    private javax.swing.JTextField txtWorkPhoneNumber;
    private javax.swing.JTextField txtWorkState;
    private javax.swing.JTextField txtWorkStreetName;
    private javax.swing.JTextField txtWorkUnitNumber;
    private javax.swing.JTextField txtWorkZip;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables

    private void setFieldsEditable() {
    txtFirstName.setEditable(true);
    txtLastName.setEditable(true);
    txtAge.setEditable(true);
    txtSocialNumber.setEditable(true);
    txtStreetName.setEditable(true);
    txtUnitNumber.setEditable(true);
    txtCity.setEditable(true);
    txtState.setEditable(true);
    txtZip.setEditable(true);
    txtPhoneNumber.setEditable(true);
    txtWorkStreetName.setEditable(true);
    txtWorkUnitNumber.setEditable(true);
    txtWorkCity.setEditable(true);
    txtWorkState.setEditable(true);
    txtWorkZip.setEditable(true);
    txtWorkPhoneNumber.setEditable(true);
    Color whiteBackground = Color.WHITE;
    txtFirstName.setBackground(whiteBackground);
    txtLastName.setBackground(whiteBackground);
    txtAge.setBackground(whiteBackground);
    txtSocialNumber.setBackground(whiteBackground);
    txtStreetName.setBackground(whiteBackground);
    txtUnitNumber.setBackground(whiteBackground);
    txtCity.setBackground(whiteBackground);
    txtState.setBackground(whiteBackground);
    txtZip.setBackground(whiteBackground);
    txtPhoneNumber.setBackground(whiteBackground);
    txtWorkStreetName.setBackground(whiteBackground);
    txtWorkUnitNumber.setBackground(whiteBackground);
    txtWorkCity.setBackground(whiteBackground);
    txtWorkState.setBackground(whiteBackground);
    txtWorkZip.setBackground(whiteBackground);
    txtWorkPhoneNumber.setBackground(whiteBackground);
    
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewPerson.getModel();
        
        // Clear the existing rows in the table
        model.setRowCount(0);
        
        // Iterate through the list of people in the person directory
        for (Person p : personDirectory.getPersonList()) {
            // Create an array of objects for each row
            Object[] row = new Object[6];
            row[0] = p.getFirstname();  // First Name
            row[1] = p.getLastname();   // Last Name
            row[2] = p.getHomeAddress().getCity(); // Home City
            row[3] = p.getHomeAddress().getZipCode(); // Home Zip
            row[4] = p.getWorkAddress().getCity();  // Work City
            row[5] = p.getWorkAddress().getZipCode();  // Work Zip
            
            // Add the row to the table model
            model.addRow(row);
        }
    }





}
